name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# --- ADD THIS BLOCK ---
permissions:
  contents: write
# ----------------------

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html/  # Based on your directory structure
